// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuisNGqfEl7i8v9LecS8vII1xoDIwrMeQ',
    appId: '1:431241685910:web:fc561161bbb864b96e0bb7',
    messagingSenderId: '431241685910',
    projectId: 'travelin-e2b24',
    authDomain: 'travelin-e2b24.firebaseapp.com',
    storageBucket: 'travelin-e2b24.appspot.com',
    measurementId: 'G-R9LX9LSXMD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0PUyYA5uQQYalZptGoSg13pXH7XL-TaA',
    appId: '1:431241685910:android:2fe36b88b8d226706e0bb7',
    messagingSenderId: '431241685910',
    projectId: 'travelin-e2b24',
    storageBucket: 'travelin-e2b24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh7YwVI3KPCAjKgojH6pMqVNSWhkJgtko',
    appId: '1:431241685910:ios:e0f0776216f177c96e0bb7',
    messagingSenderId: '431241685910',
    projectId: 'travelin-e2b24',
    storageBucket: 'travelin-e2b24.appspot.com',
    iosBundleId: 'com.example.travelin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDh7YwVI3KPCAjKgojH6pMqVNSWhkJgtko',
    appId: '1:431241685910:ios:1739d6de3aec031c6e0bb7',
    messagingSenderId: '431241685910',
    projectId: 'travelin-e2b24',
    storageBucket: 'travelin-e2b24.appspot.com',
    iosBundleId: 'com.example.travelin.RunnerTests',
  );
}
